### ISSUE TITLE
Fatal Exception when selecting About in settings

### ISSUE THREAD

**Issue by syphyr** [AllanWang/Frost-for-Facebook#1925]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Fatal exception occurs when selecting "About Frost for Facebook" in settings

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to settings
2. Click on 'About Frost for Facebook'

**Details (please provide at least the app version):**
 - App Version: 3.2.0
 - Device: T813
 - Android Version: 7.1

**Logs/Screenshots:**

```
11-26 22:02:06.432 23854 23854 E AndroidRuntime: FATAL EXCEPTION: main
11-26 22:02:06.432 23854 23854 E AndroidRuntime: Process: com.pitchedapps.frost, PID: 23854
11-26 22:02:06.432 23854 23854 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pitchedapps.frost/com.pitchedapps.frost.activities.AboutActivity}: java.lang.IllegalStateException: Please provide the required library data via the available APIs.
11-26 22:02:06.432 23854 23854 E AndroidRuntime: Depending on the platform this can be done for example via `LibsBuilder().withJson()`.
11-26 22:02:06.432 23854 23854 E AndroidRuntime: For Android there exists an `LibsBuilder.withContext()`, automatically loading the `aboutlibraries.json` file from the `raw` resources folder.
11-26 22:02:06.432 23854 23854 E AndroidRuntime: When using compose or other parent modules, please check their corresponding APIs.
11-26 22:02:06.432 23854 23854 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
11-26 22:02:06.432 23854 23854 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
11-26 22:02:06.432 23854 23854 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-26 22:02:06.432 23854 23854 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
11-26 22:02:06.432 23854 23854 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-26 22:02:06.432 23854 23854 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-26 22:02:06.432 23854 23854 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
11-26 22:02:06.432 23854 23854 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 22:02:06.432 23854 23854 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-26 22:02:06.432 23854 23854 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
11-26 22:02:06.432 23854 23854 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Please provide the required library data via the available APIs.
```

**Comment by mormegil-cz** [comment]
Yeah, I noticed this as well. Probably a duplicate of #1915?
